name: CD
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build 🛠️
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10.19
      - run: npm i
      - run: npm run test
      - run: npm run lint
      - run: npm run prebuild
  
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: publish-npm ✈️
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: deploy to GH-Pages 🚀
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dev
