name: BUILD 🔧
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build 🛠️
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10.19
      - run: npm i
      - run: npm run test
      - run: npm run lint
      - run: npm run prebuild
  
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: publish-npm ✈️
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: deploy to GH-Pages 🚀
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          node-version: 10.19
          registry-url: https://registry.npmjs.org/
          branch: gh-pages # The branch the action should deploy to.
          folder: dev # The folder the action should deploy.
      - run: npm i
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
